<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20714" started-at="2019-09-29T14:15:25 IST" finished-at="2019-09-29T14:15:46 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20714" started-at="2019-09-29T14:15:25 IST" finished-at="2019-09-29T14:15:46 IST">
      <class name="com.log4.tests.LoginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.log4.tests.LoginTest@32eebfca]" name="setup" is-config="true" duration-ms="10498" started-at="2019-09-29T14:15:25 IST" finished-at="2019-09-29T14:15:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="freeCrmTitleTest()[pri:1, instance:com.log4.tests.LoginTest@32eebfca]" name="freeCrmTitleTest" duration-ms="33" started-at="2019-09-29T14:15:36 IST" finished-at="2019-09-29T14:15:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- freeCrmTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.log4.tests.LoginTest@32eebfca]" name="tearDown" is-config="true" duration-ms="688" started-at="2019-09-29T14:15:36 IST" finished-at="2019-09-29T14:15:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.log4.tests.LoginTest@32eebfca]" name="setup" is-config="true" duration-ms="8687" started-at="2019-09-29T14:15:37 IST" finished-at="2019-09-29T14:15:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="freemCRMLogoTest()[pri:2, instance:com.log4.tests.LoginTest@32eebfca]" name="freemCRMLogoTest" duration-ms="51" started-at="2019-09-29T14:15:45 IST" finished-at="2019-09-29T14:15:45 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.log4.tests.LoginTest.freemCRMLogoTest(LoginTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- freemCRMLogoTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.log4.tests.LoginTest@32eebfca]" name="tearDown" is-config="true" duration-ms="690" started-at="2019-09-29T14:15:45 IST" finished-at="2019-09-29T14:15:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.log4.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
